name: Аудит
standard: ГОСТ Р ИСО 9001-2015
definition: Пример конфигурационного файла для работы программы аудита
author:
  name: Roman
  second name: Lupashko
  status: student

fields:
  - &mark_field_o_o
    name: organization object
    required: True
  - &mark_field_o_s
    name: organization subject
    required: True
  - &mark_field_r_c
    name: responsible contractor
    required: True
  - &mark_field_r_p
    name: responsible person
    required: True
  - &mark_field_a_t
    name: audit type
    options:
      - Внутренний
      - Сторонний
    required: True

questions:
  - id: &quest_id_1 1
    enumerator: 1
    question: Какие процессы в организации являются ключевыми?
    options:
      - id: 1
        value: Все процессы
      - id: 2
        value: Только процессы, связанные с производством
      - id: 3
        value: Только процессы, связанные с управлением
      - id: 4
        value: Только процессы, связанные с продажами
    true_selected: [1,]

  - id: &quest_id_2 2
    enumerator: 2
    question: Какие документы используются для управления процессами?
    options:
      - id: 1
        value: Только инструкции по работе
      - id: 2
        value: Только технические задания
      - id: 3
        value: Инструкции по работе и технические задания
      - id: 4
        value: Инструкции по работе, технические задания и регламенты
    true_selected: [1, 2]

report:
  template: >
    header:
      author:
        name: {{ author["name"] }}
        sur name: {{ author['second name'] }}
        status: {{ author['status'] }}
      fields:
        {% for field in fields %}
        - name: {{ field.name }}
          value: {{ field.value }}  
        {% endfor %}
    body:
      report:
        score: {{ score }}
        error_quest:
        {% for quest in questions %}
          {% if not quest.right %}
          - text: {{ quest.text }}
            selected_text:
            {% for sel_id in quest.selected %}
              - {{ quest.options[sel_id-1]["value"] }}
            {% endfor %}
            true_selected_text:
              {% for sel_id in quest.true_selected %}
                - {{ quest.options[sel_id-1]["value"] }}
              {% endfor %}
          {% endif %}
        {% endfor %}
    history:    
      questions:
        {% for quest in questions %}
        - text: {{ quest.text }}
          selected_id: {{ quest.selected }}
          selected_text:
          {% for sel_id in quest.selected %}
            - {{ quest.options[sel_id-1]["value"] }}
          {% endfor %}
          right: {{ quest.right }}
        {% endfor %}
    

