name: Аудит
standard: ГОСТ Р ИСО 9001-2015
definition: Пример конфигурационного файла для работы программы аудита
author:
  name: Roman
  second name: Lupashko
  status: student

fields:
  - &mark_field_o_o
    name: organization object
    required: True
  - &mark_field_o_s
    name: organization subject
    required: True
  - &mark_field_r_c
    name: responsible contractor
    required: True
  - &mark_field_r_p
    name: responsible person
    required: True
  - &mark_field_a_t
    name: audit type
    options:
      - Внутренний
      - Сторонний
    required: True

questions:
  - id: &quest_id_1 1
    enumerator: 1
    question: Какие процессы в организации являются ключевыми?
    options:
      - id: 1
        value: Все процессы
      - id: 2
        value: Только процессы, связанные с производством
      - id: 3
        value: Только процессы, связанные с управлением
      - id: 4
        value: Только процессы, связанные с продажами
    true_selected: [1,]
    recommendation: >
      Какая-то рекомендация по 1 пункту

  - id: &quest_id_2 2
    enumerator: 2
    question: Какие документы используются для управления процессами?
    options:
      - id: 1
        value: Только инструкции по работе
      - id: 2
        value: Только технические задания
      - id: 3
        value: Инструкции по работе и технические задания
      - id: 4
        value: Инструкции по работе, технические задания и регламенты
    true_selected: [1, 2]
    recommendation: >
      Какая-то рекомендация по 2 вопросу

report:
  template: >
    <!DOCTYPE html>
    <html>
    <head>
    <style>
          p {
            color: red;
          }

          @page {
            size: 21cm 29.7cm;
            margin: 20mm 20mm 20mm 20mm;
          }

          body {
            size: 21cm 29.7cm;
            margin: 20mm 20mm 20mm 20mm;
            align-content: center;
          }

          h1, h2, h3, p {
            max-width: max-content;
          }
    
          .flex {
            display: flex;
            align-items: center;
          }
          
          .flex > * {
            margin-right: 10px;
            #padding: 10px;
          }
          
    </style>
    <title>Отчет по аудиту</title>
    </head>
    <body>
    
    <header>
      <h1>Отчет по аудиту</h1>
      <h2>По стандарту {{ standard }}</h2>
      <p>{{ definition }}</p>
      <div class="flex">
        <p>{{ author["name"] }}</p> <p>{{ author["second name"] }}</p>
        <p>{{ author["status"] }}</p>
      </div>
      <div>
        {% for field in fields %}
        <div class="flex"> <p>{{ field.name }}</p> <p>{{ field.value }}</p></div>
        {% endfor %}
      </div>
    </header>
    
    <main>
      <h2>Основная часть</h2>
      <div class="flex">
        <p>Score</p>
        <p>{{ score }}</p>
      </div>
      <div>
        <h3>Recommendation</h3>
        <ul>
        {% for quest in questions %}
          {% if not quest.right %}
          <li>{{ quest.recommendation }}</li>
          {% endif %}
        {% endfor %}
        </ul>
      </div>
      <hr/>
      <div class="application">
        <h2>Приложение 1</h2>
        <ul>
          {% for quest in questions %}
          <li>
            <p>{{ quest.text }}</p>
            <ul>
            {% for option in quest.options %}
              <li class="flex">
                {% if option["id"] in quest.selected%}
                <p>selected</p>
                {% endif %}
                {% if option["id"] in quest.true_selected%}
                <p>Верный ответ</p>
                {% endif %}
                {{ option["value"] }}
              </li>
            {% endfor %}
            </ul>
            <p>{{ quest.right }}</p>
          </li>
          {% endfor %}
        </ul>
      </div>
    </main>
    
    <footer>
    </footer>

    </body>
    </html>