name: Аудит
standard: ГОСТ Р ИСО 9001-2015
definition: СИСТЕМЫ МЕНЕДЖМЕНТА КАЧЕСТВА
author:
  name: Roman
  second name: Lupashko
  status: student

fields:
  - &mark_field_o_o
    name: Организация заказчик
    required: True
  - &mark_field_o_s
    name: Организация исполнитель
    required: True
  - &mark_field_r_c
    name: Ответственный исполнитель
    required: True
  - &mark_field_r_p
    name: Ответственный сотрудник
    required: True
  - &mark_field_a_t
    name: Тип проводимого аудита
    options:
      - Внутренний
      - Сторонний
    required: True

questions:
  - id: &quest_id_1 1
    enumerator: 1
    question: Какие процессы в организации являются ключевыми?
    options:
      - id: 1
        value: Все процессы
      - id: 2
        value: Только процессы, связанные с производством
      - id: 3
        value: Только процессы, связанные с управлением
      - id: 4
        value: Только процессы, связанные с продажами
    true_selected: [0,]
    recommendation: >
      Какая-то рекомендация по 1 пункту

  - id: &quest_id_2 2
    enumerator: 2
    question: Какие документы используются для управления процессами?
    options:
      - id: 1
        value: Только инструкции по работе
      - id: 2
        value: Только технические задания
      - id: 3
        value: Инструкции по работе и технические задания
      - id: 4
        value: Инструкции по работе, технические задания и регламенты
    true_selected: [0, 1]
    recommendation: >
      Какая-то рекомендация по 2 вопросу

  - id: &quest_id_3 3
    enumerator: 3
    question: Какие меры принимаются для улучшения процессов?
    options:
      - id: 1
        value: Никакие меры не принимаются
      - id: 2
        value: Процессы периодически анализируются и улучшаются
      - id: 3
        value: Процессы анализируются и улучшаются только при возникновении проблем
      - id: 4
        value: Процессы анализируются и улучшаются только при проведении внешней аудитории
    true_selected: [ 1 ]
    recommendation: >
      Какая-то рекомендация по 3 вопросу

  - id: &quest_id_4 4
    enumerator: 4
    question: Какие показатели используются для оценки эффективности процессов?
    options:
      - id: 1
        value: Только финансовые показатели
      - id: 2
        value: Только показатели качества продукции или услуг
      - id: 3
        value: Финансовые показатели и показатели качества продукции или услуг
      - id: 4
        value: Никакие показатели не используются для оценки эффективности процессов
    true_selected: [ 1 ]
    recommendation: >
      Какая-то рекомендация по 4 вопросу

  - id: &quest_id_5 5
    enumerator: 5
    question: Какие меры принимаются для устранения несоответствий?
    options:
      - id: 1
        value: Никакие меры не принимаются
      - id: 2
        value: Несоответствия устраняются только при проведении внешней аудитории
      - id: 3
        value: Несоответствия устраняются только при возникновении проблем
      - id: 4
        value: Несоответствия устраняются незамедлительно
    true_selected: [ 3 ]
    recommendation: >
      Какая-то рекомендация по 5 вопросу

  - id: &quest_id_6 6
    enumerator: 6
    question: Какие процессы в организации являются критическими?
    options:
      - id: 1
        value: Все процессы равны по значимости
      - id: 2
        value: Только те процессы, которые влияют на качество продукции или услуг
      - id: 3
        value: Только те процессы, которые связаны с управлением персоналом
      - id: 4
        value: Только те процессы, которые связаны с закупками
    true_selected: [ 1 ]
    recommendation: >
      Какая-то рекомендация по 6 вопросу

  - id: &quest_id_7 7
    enumerator: 7
    question: Какие меры принимаются для управления рисками?
    options:
      - id: 1
        value: Никакие меры не принимаются
      - id: 2
        value: Риски периодически анализируются и оцениваются
      - id: 3
        value: Риски анализируются и оцениваются только при возникновении проблем
      - id: 4
        value: Риски анализируются и оцениваются периодически, а также при изменении условий
    true_selected: [ 3 ]
    recommendation: >
      Какая-то рекомендация по 7 вопросу

  - id: &quest_id_8 8
    enumerator: 8
    question: Какие меры принимаются для управления изменениями?
    options:
      - id: 1
        value: Никакие меры не принимаются
      - id: 2
        value: Изменения планируются и контролируются
      - id: 3
        value: Изменения планируются и контролируются только при проведении внешней аудитории
      - id: 4
        value: Изменения планируются и контролируются только при возникновении проблем
    true_selected: [ 1 ]
    recommendation: >
      Какая-то рекомендация по 8 вопросу

  - id: &quest_id_9 9
    enumerator: 9
    question: Какие меры принимаются для управления документами?
    options:
      - id: 1
        value: Никакие меры не принимаются
      - id: 2
        value: Документы хранятся в произвольном порядке
      - id: 3
        value: Документы хранятся в порядке, определяемом организацией
      - id: 4
        value: Документы хранятся в порядке, определяемом организацией, и доступны для использования
    true_selected: [ 3 ]
    recommendation: >
      Какая-то рекомендация по 9 вопросу

  - id: &quest_id_10 10
    enumerator: 10
    question: Какие меры принимаются для обеспечения качества продукции или услуг?
    options:
      - id: 1
        value: Никакие меры не принимаются
      - id: 2
        value: Процессы контроля качества продукции или услуг регулярно проводятся
      - id: 3
        value: Процессы контроля качества продукции или услуг проводятся только при возникновении проблем
      - id: 4
        value: Процессы контроля качества продукции или услуг проводятся только при проведении внешней аудитории
    true_selected: [ 1 ]
    recommendation: >
      Какая-то рекомендация по 10 вопросу

  - id: &quest_id_11 11
    enumerator: 11
    question: Какие меры принимаются для управления ресурсами?
    options:
      - id: 1
        value: Никакие меры не принимаются
      - id: 2
        value: Ресурсы управляются только при возникновении проблем
      - id: 3
        value: Ресурсы управляются только при проведении внешней аудитории
      - id: 4
        value: Ресурсы управляются периодически
    true_selected: [ 3 ]
    recommendation: >
      Какая-то рекомендация по 11 вопросу

  - id: &quest_id_12 12
    enumerator: 12
    question: Какие меры принимаются для управления персоналом?
    options:
      - id: 1
        value: Никакие меры не принимаются
      - id: 2
        value: Персонал обучается только при возникновении проблем
      - id: 3
        value: Персонал обучается только при проведении внешней аудитории
      - id: 4
        value: Персонал обучается периодически
    true_selected: [ 3 ]
    recommendation: >
      Какая-то рекомендация по 12 вопросу

  - id: &quest_id_13 13
    enumerator: 13
    question: Какие меры принимаются для управления оборудованием?
    options:
      - id: 1
        value: Никакие меры не принимаются
      - id: 2
        value: Оборудование обслуживается только при возникновении проблем
      - id: 3
        value: Оборудование обслуживается только при проведении внешней аудитории
      - id: 4
        value: Оборудование обслуживается периодически
    true_selected: [ 3 ]
    recommendation: >
      Какая-то рекомендация по 13 вопросу

  - id: &quest_id_14 14
    enumerator: 14
    question: Какие меры принимаются для управления поставщиками?
    options:
      - id: 1
        value: Никакие меры не принимаются
      - id: 2
        value: Поставщики выбираются произвольно
      - id: 3
        value: Поставщики выбираются на основе личных отношений с руководством организации
      - id: 4
        value: Поставщики выбираются на основе оценки их способности удовлетворять требованиям организации
    true_selected: [ 3 ]
    recommendation: >
      Какая-то рекомендация по 14 вопросу

  - id: &quest_id_15 15
    enumerator: 15
    question: Какие меры принимаются для управления клиентами?
    options:
      - id: 1
        value: Никакие меры не принимаются
      - id: 2
        value: Клиенты удовлетворяются только при проведении внешней аудитории
      - id: 3
        value: Клиенты удовлетворяются только при возникновении проблем
      - id: 4
        value: Клиенты удовлетворяются периодически
    true_selected: [ 3 ]
    recommendation: >
      Какая-то рекомендация по 15 вопросу

  - id: &quest_id_16 16
    enumerator: 16
    question: Какие меры принимаются для управления информацией?
    options:
      - id: 1
        value: Никакие меры не принимаются
      - id: 2
        value: Информация хранится в произвольном порядке
      - id: 3
        value: Информация хранится в порядке, определяемом организацией
      - id: 4
        value: Информация хранится в порядке, определяемом организацией, и доступна для использования
    true_selected: [ 3 ]
    recommendation: >
      Какая-то рекомендация по 16 вопросу

report:
  template: >
    <!DOCTYPE html>
    <html>
    <head>
    <style>
          p {
            color: red;
          }

          @page {
            size: 21cm 29.7cm;
            margin: 20mm 20mm 20mm 20mm;
          }

          body {
            size: 21cm 29.7cm;
            margin: 20mm 20mm 20mm 20mm;
            align-content: center;
          }

          h1, h2, h3, p {
            max-width: max-content;
          }
    
          .flex {
            display: flex;
            align-items: center;
          }
          
          .flex > * {
            margin-right: 10px;
            #padding: 10px;
          }
          
    </style>
    <title>Отчет по аудиту</title>
    </head>
    <body>
    
    <header>
      <h1>Отчет по аудиту</h1>
      <h2>По стандарту {{ standard }}</h2>
      <p>{{ definition }}</p>
      <div class="flex">
        <p>{{ author["name"] }}</p> <p>{{ author["second name"] }}</p>
        <p>{{ author["status"] }}</p>
      </div>
      <div>
        {% for field in fields %}
        <div class="flex"> <p>{{ field.name }}</p> <p>{{ field.value }}</p></div>
        {% endfor %}
      </div>
    </header>
    
    <main>
      <h2>Основная часть</h2>
      <div class="flex">
        <p>Score</p>
        <p>{{ score }}</p>
      </div>
      <div>
        <h3>Recommendation</h3>
        <ul>
        {% for quest in questions %}
          {% if not quest.right %}
          <li>{{ quest.recommendation }}</li>
          {% endif %}
        {% endfor %}
        </ul>
      </div>
      <hr/>
      <div class="application">
        <h2>Приложение 1</h2>
        <ul>
          {% for quest in questions %}
          <li>
            <p>{{ quest.text }}</p>
            <ul>
            {% for option in quest.options %}
              <li class="flex">
                {% if option["id"] in quest.selected%}
                <p>selected</p>
                {% endif %}
                {% if option["id"] in quest.true_selected%}
                <p>Верный ответ</p>
                {% endif %}
                {{ option["value"] }}
              </li>
            {% endfor %}
            </ul>
            <p>{{ quest.right }}</p>
          </li>
          {% endfor %}
        </ul>
      </div>
    </main>
    
    <footer>
    </footer>

    </body>
    </html>